# Algorithm Preparation

### Connecting to the database

In [62]:
import kmedoids
import numpy as np
import pandas as pd
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import create_engine

from flaskr import Clustering
from flaskr import CollaborativeFiltering
from flaskr import UserPreferences, ActivityAttributes
from flaskr.clustering import find_number_of_optimal_clusters
from flaskr.cosine_similarity_wrapper import CosineSimilarityWrapper
from flaskr.geocoding import calculate_spatial_distances

db = SQLAlchemy()


def get_db_connection():
    engine = create_engine("postgresql://admin:admin@localhost:5432/sila-db")
    return engine

engine = get_db_connection()

### Fetching the data

In [63]:
# Fetch explicit ratings (studio reviews)
query_ratings = """
SELECT r.application_user_id, r.studio_id, r.rating
FROM review r;
"""
df_ratings = pd.read_sql(query_ratings, engine)

# Fetch implicit feedback (user visit history)
query_visits = """
SELECT *
FROM user_studio_activities;
"""
df_visits = pd.read_sql(query_visits, engine)

# Fetch implicit feedback (user visit history)
query_likes = """
SELECT *
FROM favourite_studios;
"""
df_likes = pd.read_sql(query_likes, engine)

# Fetch studio activities
query_studio_activities = """
SELECT *
FROM studio_activity sa 
WHERE sa.date_time > CURRENT_TIMESTAMP;
"""
df_studio_activities = pd.read_sql(query_studio_activities, engine)

# Fetch studios
query_studios = """
SELECT *
FROM studio;
"""
df_studios = pd.read_sql(query_studios, engine)

query_activity_studio = """
SELECT ssa.studio_studio_id,
        ssa.studio_activities_studio_activity_id
FROM studio_studio_activities ssa;
"""
df_activity_studio_mapping = pd.read_sql(query_activity_studio, engine)

# Fetch user data
query_users = """
SELECT au.application_user_id, au.location, au.longitude, au.latitude
FROM application_user au, application_user_preferences aup
WHERE au.application_user_id = aup.application_user_id
    AND au.is_admin = FALSE AND au.is_studio_admin = FALSE
    AND au.longitude <> 0 AND au.latitude <> 0;
"""
df_users = pd.read_sql(query_users, engine)

# Fetch recommendation cluster data
query_clusters = """
SELECT * FROM recommendation_cluster;
"""
df_recommendation_clusters = pd.read_sql(query_clusters, engine)

# Fetch user preferences
query_user_preferences_for_cluster = """
SELECT * FROM application_user_preferences;
"""
df_user_preferences = pd.read_sql(query_user_preferences_for_cluster, engine)

# Fetch activity attributes
query_activity_attributes = """
SELECT *
FROM studio_activity_preferences sap
JOIN studio_activity sa ON sap.id = sa.preferences_id
WHERE sa.date_time > CURRENT_TIMESTAMP;
"""
df_activity_attributes = pd.read_sql(query_activity_attributes, engine)

### Assign the user preferences and activity attributes to their corresponding classes

In [64]:
user_preferences_list_for_cluster = []
for _, row in df_user_preferences.iterrows():
    pref = UserPreferences(row)
    user_preferences_list_for_cluster.append(pref)

activity_attributes_list = []
for _, row in df_activity_attributes.iterrows():
    pref = ActivityAttributes(row)
    activity_attributes_list.append(pref)

# Algorithm Execution

## Content-based Filtering 

For this purpose, we use the "/on-preferences" endpoint

### Perform Clustering

In [65]:
pam_clustering = Clustering(activityAttributes=activity_attributes_list,
                            userPreferences=user_preferences_list_for_cluster,
                            df_users=df_users)

alpha = 0.8  # can be adjusted

spatial_distances = np.ndarray
try:
    spatial_distances = calculate_spatial_distances(df_users)
except ValueError as e:
    print("Error calculating spatial distances:", e)

# plot
# save_matrix_image(spatial_distances, filename="spatial_distances.png")

filtering = CosineSimilarityWrapper(users_preferences=user_preferences_list_for_cluster,
                                    activities_attributes=activity_attributes_list)
cosine_sim = filtering.calculate_cosine_similarity_users()

print("Cosine similarity matrix:")
print(cosine_sim)

print("Spatial distance matrix:")
print(spatial_distances)

combined = alpha * cosine_sim + (1 - alpha) * spatial_distances

print("Combined matrix:")
print(combined)

Cosine similarity matrix:
[[1.         0.31596674 0.45869915 ... 0.41297239 0.18743765 0.30001015]
 [0.31596674 1.         0.46662826 ... 0.25841254 0.63595145 0.5419311 ]
 [0.45869915 0.46662826 1.         ... 0.37514585 0.51226913 0.4461593 ]
 ...
 [0.41297239 0.25841254 0.37514585 ... 1.         0.2832067  0.3610995 ]
 [0.18743765 0.63595145 0.51226913 ... 0.2832067  1.         0.68474301]
 [0.30001015 0.5419311  0.4461593  ... 0.3610995  0.68474301 1.        ]]
Spatial distance matrix:
[[1.         0.93945938 0.68099938 ... 0.92275286 0.51810337 0.99989317]
 [0.93945938 1.         0.50136481 ... 0.99781532 0.39026858 0.93514472]
 [0.68099938 0.50136481 1.         ... 0.48904147 0.92168343 0.68901495]
 ...
 [0.92275286 0.99781532 0.48904147 ... 1.         0.39044741 0.91816096]
 [0.51810337 0.39026858 0.92168343 ... 0.39044741 1.         0.52504529]
 [0.99989317 0.93514472 0.68901495 ... 0.91816096 0.52504529 1.        ]]
Combined matrix:
[[1.         0.44066527 0.5031592  ... 0.514

In [66]:
optimal_clusters = find_number_of_optimal_clusters(combined_distances=combined)

# Perform PAM clustering with the optimal number of clusters
pam = kmedoids.KMedoids(n_clusters=optimal_clusters, metric='euclidean', random_state=123)
cluster_labels = pam.fit_predict(combined)

results = {
    "optimal_clusters": optimal_clusters,
    "cluster_labels": cluster_labels
}

results

2025-02-03 13:00:58 - INFO - flaskr.clustering - Optimal number of clusters determined by Elbow Method: 8


{'optimal_clusters': 8,
 'cluster_labels': array([1, 6, 3, 6, 3, 2, 5, 4, 5, 7, 3, 0, 4, 3, 2, 2, 6, 3, 3, 7, 6, 1,
        0, 4, 7, 6, 7, 0, 7, 2, 0, 0, 3, 7, 4, 5, 0, 3, 6, 0, 7, 7, 5, 1,
        6, 6, 7, 2, 1, 6, 7, 2, 5, 1, 1, 7, 7, 4, 5, 6, 1, 4, 3, 4, 3, 6,
        6, 5, 1, 2, 7, 4, 7, 7, 2, 7, 5, 7, 1, 2, 0, 0, 5, 2, 0, 7, 2, 5,
        6, 3, 2, 5, 0, 1, 6, 4, 4, 7, 0, 3, 4, 6, 1, 0, 5, 5, 2, 3, 3, 5,
        3, 5, 7, 6, 3, 6, 0, 3, 7, 4, 2, 5, 6, 4, 0, 5, 6, 7, 3, 6, 6, 0,
        6, 5, 1, 7, 4, 7, 2, 2, 3, 1, 5, 7, 3, 6, 4, 6, 3, 7, 3, 5, 4, 6,
        4, 6, 0, 0, 7, 5, 1, 6, 4, 0, 0, 5, 2, 4, 0, 1, 5, 5, 0, 3, 6, 6,
        7, 4, 5, 5, 1, 1, 6, 0, 6, 4, 4, 1, 4, 1, 1, 4, 2, 2, 0, 5, 4, 2,
        0, 0, 6, 3, 6, 7, 7, 5, 1, 1, 6, 5, 0, 6, 1, 1, 6, 5, 0, 5, 3, 7,
        5, 2, 6, 0, 4, 5, 3, 5, 7, 6, 0, 7, 7, 6, 5, 6, 3, 3, 2, 3, 6, 6,
        4, 7, 0, 4, 2, 0, 0, 5, 7, 0, 0, 5, 4, 3, 7, 6, 3, 3, 4, 4, 5, 5,
        0, 7, 4, 2, 6, 3, 3, 5, 4, 7, 3, 2, 0, 6, 3, 6, 2, 0, 6, 3, 4,

### Prepare the DB

In [67]:
from sqlalchemy import text

existing_cluster_ids = set(int(x) for x in df_recommendation_clusters["recommendation_cluster_id"].tolist())

new_cluster_ids = set(int(x) for x in cluster_labels) - existing_cluster_ids  # Convert to int

print(new_cluster_ids)

if new_cluster_ids:
    print(f"Inserting new recommendation_cluster instances: {new_cluster_ids}")
    with engine.begin() as conn:
        conn.execute(
            text("INSERT INTO recommendation_cluster (recommendation_cluster_id) VALUES (:cluster_id)"),
            [{"cluster_id": cluster_id} for cluster_id in new_cluster_ids]
        )

update_data = [
    {"cluster_id": int(cluster_labels[i]), "user_id": int(row["application_user_id"])}
    for i, row in df_users.iterrows()
]

with engine.begin() as conn:
    conn.execute(
        text("UPDATE application_user "
             "SET recommendation_cluster_id = :cluster_id "
             "WHERE application_user_id = :user_id"),
        update_data
    )

set()


In [68]:
################################
# Delete existing cluster-activity mappings in the DB
################################

query_recommendation_cluster_recommended_activities = """
    SELECT * FROM recommendation_cluster_recommended_activities;
    """
df_recommendation_cluster_recommended_activities = pd.read_sql(
    query_recommendation_cluster_recommended_activities, engine)
recommendation_cluster_recommendation_cluster_ids = df_recommendation_cluster_recommended_activities[
    "recommendation_cluster_recommendation_cluster_id"].tolist()

if recommendation_cluster_recommendation_cluster_ids:
    # if clustering results already are saved, drop table and insert them again
    with engine.begin() as conn:
        conn.execute(
            text(
                "DELETE FROM recommendation_cluster_recommended_activities;")
        )


### Calculate similarity between preferences of user clusters and activity attributes

In [69]:
query_user_preferences_with_cluster_id = f"""
SELECT aup.*, au.recommendation_cluster_id FROM application_user_preferences aup, application_user au
WHERE au.recommendation_cluster_id IS NOT NULL AND aup.application_user_id = au.application_user_id;
"""
df_user_preferences_with_cluster_id = pd.read_sql(query_user_preferences_with_cluster_id, engine)

recommendations_to_insert = []
for label in set(cluster_labels):

    # Fetch user preferences for each cluster with pandas
    df_cleaned = df_user_preferences_with_cluster_id.loc[
        df_user_preferences_with_cluster_id['recommendation_cluster_id'] == label]

    user_preferences_list_for_cluster = []
    for _, row in df_cleaned.iterrows():
        pref = UserPreferences(row)
        user_preferences_list_for_cluster.append(pref)

    recommended_activities = pam_clustering.user_cluster_similarity_with_activity_attributes(
        user_preferences_for_cluster=user_preferences_list_for_cluster
    )

    for activity_id in recommended_activities.keys():
        recommendations_to_insert.append({
            "label": int(label),
            "activity_id": activity_id
        })

recommendations_to_insert   


2025-02-03 13:01:02 - INFO - flaskr.clustering - Top 5 activity recommendations based on cluster similarity: {5: np.float64(2.5388662425334947), 6: np.float64(2.4918920538423133), 7: np.float64(2.4918920538423133), 3: np.float64(2.475752525880963), 10: np.float64(2.4652781148262073)}
2025-02-03 13:01:02 - INFO - flaskr.clustering - Top 5 activity recommendations based on cluster similarity: {3: np.float64(2.5439847497734034), 8: np.float64(2.5061517232954977), 9: np.float64(2.5061517232954977), 10: np.float64(2.4898555241165), 11: np.float64(2.4898555241165)}
2025-02-03 13:01:02 - INFO - flaskr.clustering - Top 5 activity recommendations based on cluster similarity: {10: np.float64(2.536566958184326), 11: np.float64(2.536566958184326), 12: np.float64(2.536566958184326), 13: np.float64(2.536566958184326), 14: np.float64(2.536566958184326)}
2025-02-03 13:01:02 - INFO - flaskr.clustering - Top 5 activity recommendations based on cluster similarity: {6: np.float64(2.585868031867739), 7: np

[{'label': 0, 'activity_id': 5},
 {'label': 0, 'activity_id': 6},
 {'label': 0, 'activity_id': 7},
 {'label': 0, 'activity_id': 3},
 {'label': 0, 'activity_id': 10},
 {'label': 1, 'activity_id': 3},
 {'label': 1, 'activity_id': 8},
 {'label': 1, 'activity_id': 9},
 {'label': 1, 'activity_id': 10},
 {'label': 1, 'activity_id': 11},
 {'label': 2, 'activity_id': 10},
 {'label': 2, 'activity_id': 11},
 {'label': 2, 'activity_id': 12},
 {'label': 2, 'activity_id': 13},
 {'label': 2, 'activity_id': 14},
 {'label': 3, 'activity_id': 6},
 {'label': 3, 'activity_id': 7},
 {'label': 3, 'activity_id': 5},
 {'label': 3, 'activity_id': 8},
 {'label': 3, 'activity_id': 9},
 {'label': 4, 'activity_id': 1},
 {'label': 4, 'activity_id': 2},
 {'label': 4, 'activity_id': 3},
 {'label': 4, 'activity_id': 8},
 {'label': 4, 'activity_id': 9},
 {'label': 5, 'activity_id': 10},
 {'label': 5, 'activity_id': 11},
 {'label': 5, 'activity_id': 12},
 {'label': 5, 'activity_id': 13},
 {'label': 5, 'activity_id': 14

## Collaborative Filtering 

Here we use the "/collaborative-filtering/<user_id>" endpoint

### Utility Matrix

In [72]:
# explicitly convert indices and columns to integers
df_users['application_user_id'] = df_users['application_user_id'].astype(int)
df_studios['studio_id'] = df_studios['studio_id'].astype(int)

utility_matrix = pd.DataFrame(index=df_users['application_user_id'], columns=df_studios['studio_id'])

# studio ratings
for _, row in df_ratings.iterrows():
    user_id = int(row['application_user_id'])
    studio_id = int(row['studio_id'])
    value = row['rating']
    if user_id in utility_matrix.index and studio_id in utility_matrix.columns and pd.notna(value):
        # subtract 3 from the rating to make it 0-based
        utility_matrix.loc[user_id, studio_id] = value - 3

# liked studios
for _, row in df_likes.iterrows():
    user_id = int(row['application_user_id'])
    studio_id = int(row['studio_id'])
    if user_id in utility_matrix.index and studio_id in utility_matrix.columns:
        utility_matrix.loc[user_id, studio_id] += 1

# studio visits
for _, row in df_visits.iterrows():
    user_id = int(row['application_user_id'])
    activity_id = int(row['studio_activity_id'])

    # Ensure activity_id exists in the mapping before accessing it
    studio_id_series = df_activity_studio_mapping.loc[
        df_activity_studio_mapping[
            'studio_activities_studio_activity_id'] == activity_id, 'studio_studio_id'
    ]

    if not studio_id_series.empty:
        studio_id = int(studio_id_series.iloc[0])

        if user_id in utility_matrix.index and studio_id in utility_matrix.columns:
            # Add 0.2 to final value for every visit
            utility_matrix.loc[user_id, studio_id] += 0.2

utility_matrix

studio_id             6    7    8    9    10   11   12   13   14   15  ...  \
application_user_id                                                    ...   
6                    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...   
9                    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...   
12                   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...   
15                   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...   
18                   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...   
...                  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
998                  NaN  NaN  NaN  NaN  NaN  NaN -0.8  1.2  NaN  NaN  ...   
1000                 1.2  NaN  NaN  0.2  NaN -0.8  NaN  NaN  NaN  NaN  ...   
1001                 NaN  NaN  NaN  NaN  NaN  0.2  NaN  NaN  NaN  NaN  ...   
1003                -1.8  NaN  NaN  NaN  NaN  NaN  0.2  NaN  2.2  NaN  ...   
1004                 2.2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...   

studio_id             48   49   50   51   52   53   54   55   56   1   
application_user_id                                                    
6                    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
9                    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
12                   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
15                   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
18                   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
...                  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
998                  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
1000                 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
1001                 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN -0.6  
1003                 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
1004                 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  

[1000 rows x 56 columns]

In [73]:
user_id = 458 # check in the DB that the user is not an admin, studio admin or locked

collab = CollaborativeFiltering(df_ratings, df_users, df_studio_activities, df_activity_studio_mapping,
                                df_visits, df_studios, df_likes)

recommended_activities = collab.recommend_items(int(user_id), 10)
recommended_activities

2025-02-03 13:04:46 - INFO - flaskr.collaborative_filtering - Generated utility matrix:
studio_id             6    7    8    9    10   11   12   13   14   15  ...  \
application_user_id                                                    ...   
6                    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...   
9                    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...   
12                   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...   
15                   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...   
18                   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...   
...                  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
998                  NaN  NaN  NaN  NaN  NaN  NaN -0.8  1.2  NaN  NaN  ...   
1000                 1.2  NaN  NaN  0.2  NaN -0.8  NaN  NaN  NaN  NaN  ...   
1001                 NaN  NaN  NaN  NaN  NaN  0.2  NaN  NaN  NaN  NaN  ...   
1003                -1.8  NaN  NaN  NaN  NaN  NaN  0.2

studio_id  predicted_ratings
12         18           1.281015
7          13           1.262509
13         20           1.247105
14         21           1.172143
8          14           1.138709
36          4           1.121238
37          3           1.103875
11         17           1.081113
4          10           1.071651
9          15           1.069622